### ISSUE TITLE
data arrangement

### ISSUE THREAD

**Issue by ronnyshalev** [Jack-Etheredge/Brain-Tumor-Segmentation-3D-UNet-CNN#1]
Hi,

Thanks for sharing your code.

I was wondering if you could explain how you arrange the data. It seems like the generator is looking in ./data/ for all of the files. Is there another file or function that moves the data from the original location (./HGG or ./LGG) into ./data ?

Thanks

Rony

**Comment by Jack-Etheredge** [comment]
Hey Rony,
I chose to treat LGG and HGG together, so that’s why there’s a single data directory. Beyond that, if something still doesn’t make sense, I can look through my code and my AWS storage to refresh my memory.
Best,
Jack
