### ISSUE TITLE
'y2' problem

### ISSUE THREAD

**Issue by Liam-Yi** [Jack-Etheredge/Brain-Tumor-Segmentation-3D-UNet-CNN#2]
Hi Jack,

Thank you for sharing.

I was wondering if you can tell me what 'y2' should be in the DataGenerator part(this may be a seemingly silly question.). I saw you marked 'list of survival days' next to it, but I failed to make the model work after trying several different methods.

Thanks a lot!

Liam

**Comment by Jack-Etheredge** [comment]
https://github.com/Jack-Etheredge/Brain-Tumor-Segmentation-3D-UNet-CNN/blob/master/BraTS_3DUNetCNN-cropping-v3-checking-predictions-callbacks-multiout-extra-layers-3preds-sequential-v5-pickle-crops.ipynb

Can you try that one?

I did the project a long time ago and never took the time to clean up the code much, so apologies for that.

I've been working on a lot of new stuff, so I haven't gone back and tried running this again on AWS, but if it doesn't work for you, I can try to find time to check through my different versions. That's the cost of doing things quick and dirty and generating a ton of different versions of the scripts. Not best practices at all from me at the time.

**Comment by Liam-Yi** [comment]
Yes, I modified the code on this basis, and now it can work properly^_^. Thank U!  I just got into the field of medical imaging, and your notebook really helped me a lot.
